TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.35 # X 方向最大速度
  min_vel_x: -0.35 # X 方向最小速速

  max_vel_y: 0.35 # X 方向最大速度
  min_vel_y: -0.35 # X 方向最小速速

  max_vel_theta:  1.0 # 
  min_vel_theta: -1.0
  min_in_place_vel_theta: 1.0

  acc_lim_x: 2.0 # X 加速限制
  acc_lim_y: 0.0 # Y 加速限制
  acc_lim_theta: 2.0 # 角速度加速限制

# Goal Tolerance Parameters，目标公差
  xy_goal_tolerance: 0.10
  yaw_goal_tolerance: 0.1

# Differential-drive robot configuration
# 是否是全向移动机器人
  holonomic_robot: true


#如果全局规划和本地规划晃动过大，设置sim——time大一点
# Forward Simulation Parameters，前进模拟参数
  sim_time: 3.0
  vx_samples: 18
  vtheta_samples: 20
  sim_granularity: 0.05